# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 239d0a4e050c446e8f51d0019fac56544c1bf94d856bda3d5eec337c2e0f514808fc5629e77f9971142f30180fcc8f3c6af9829989911416dd0b19fca43716a3

test:
  secret_key_base: 2a709b3dc7904e54bfc3e7049009863d622135db2d387ee6307027cd26fd8cb639234830bb7f41b14a1a6eb0fc15e37a56604ec094f702d7ed73aaafad43632f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
